# Generated by Django 4.2.20 on 2025-05-30 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendinguser',
            options={'verbose_name': 'пользователь для регистрации', 'verbose_name_plural': 'Регистрация пользоватей'},
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
    ]
