from typing import Final

MAX_USERS_PER_PAGE: Final[int] = 10
MAX_LOCATIONS_PER_PAGE: Final[int] = 20
MAX_SKILLS_PER_PAGE: Final[int] = 20
MAX_EDUCATIONS_PER_PAGE: Final[int] = 20
MAX_EXPERIANCE_PER_PAGE: Final[int] = 20
MAX_RESUMES_PER_PAGE: Final[int] = 20
MAX_POSITION_PER_PAGE: Final[int] = 20

MAX_USER_PATRONYMIC_LENGTH: Final[int] = 150
MAX_COUNTRY_LENGTH: Final[int] = 255
MAX_CITY_LENGTH: Final[int] = 255
MAX_GITHUB_LINK_LENGTH: Final[int] = 255
MAX_INSTITUTION_NAME_LENGTH: Final[int] = 255
MAX_EDUCATION_DEGREE_LENGTH: Final[int] = 255
MAX_FIELD_OF_STUDY_LENGTH: Final[int] = 255
MAX_COMPANY_NAME_LENGTH: Final[int] = 255
MAX_POSITION_LENGTH: Final[int] = 255
MAX_PHONE_LENGTH: Final[int] = 20
MAX_SLUG_LENGTH: Final[int] = 255
MAX_CATEGORY_LENGTH: Final[int] = 255
MAX_RESUME_TEXT_LENGTH: Final[int] = 2048

MAX_RESUME_COUNT: Final[int] = 5
MAX_RESUME_PER_PAGE_ON_FRONT: Final[int] = 5
