# Generated by Django 4.2.20 on 2025-05-19 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(blank=True, help_text='Слаг для резюме. Генерируется автоматически.', max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='hardskill',
            name='grid_column',
            field=models.PositiveIntegerField(default=1, help_text='Номер столбца в HTML-сетке для отображения этого навыка', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Столбец'),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='grid_column',
            field=models.PositiveIntegerField(default=1, help_text='Номер столбца в HTML-сетке для отображения этого навыка', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Столбец'),
        ),
        migrations.AlterField(
            model_name='user',
            name='git_hub_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя в Telegram'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('country', 'city'), name='unique_location'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.location', verbose_name='Локация'),
        ),
    ]
