# Generated by Django 4.2.20 on 2025-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_location_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardskillname',
            options={'verbose_name': 'навык', 'verbose_name_plural': 'Справочник профессиональных навыков'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-country', '-city'), 'verbose_name': 'локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='softskillname',
            options={'verbose_name': 'навык', 'verbose_name_plural': 'Справочник личностных навыков'},
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='hardskillname',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='softskillname',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
