# Generated by Django 4.2.20 on 2025-05-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_hardskillname_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hardskill',
            name='unique_hard_skill',
        ),
        migrations.RemoveConstraint(
            model_name='resumehardskill',
            name='unique_hard_skill_per_resume',
        ),
        migrations.RemoveConstraint(
            model_name='resumesoftskill',
            name='unique_soft_skill_per_resume',
        ),
        migrations.RemoveConstraint(
            model_name='softskill',
            name='unique_soft_skill',
        ),
        migrations.RemoveField(
            model_name='hardskill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='hard_skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='soft_skills',
        ),
        migrations.RemoveField(
            model_name='softskill',
            name='user',
        ),
        migrations.AddField(
            model_name='hardskill',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hard_skills', to='user.resume', verbose_name='Резюме'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softskill',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='user.resume', verbose_name='Резюме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='В качестве разделителя используйте ";"', null=True, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='resumehardskill',
            name='hard_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hardskillname'),
        ),
        migrations.AlterField(
            model_name='resumesoftskill',
            name='soft_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.softskillname'),
        ),
        migrations.AddConstraint(
            model_name='hardskill',
            constraint=models.UniqueConstraint(fields=('resume', 'skill'), name='unique_resume_hard_skill'),
        ),
        migrations.AddConstraint(
            model_name='softskill',
            constraint=models.UniqueConstraint(fields=('resume', 'skill'), name='unique_resume_soft_skill'),
        ),
    ]
