# Generated by Django 4.2.20 on 2025-05-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_hardskill_unique_hard_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumesoftskill',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resumesoftskill',
            name='soft_skill',
        ),
        migrations.DeleteModel(
            name='ResumeHardSkill',
        ),
        migrations.DeleteModel(
            name='ResumeSoftSkill',
        ),
    ]
