# Generated by Django 4.2.20 on 2025-05-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_resumesoftskill_resume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-created_at',), 'verbose_name': 'резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Должность'),
        ),
    ]
