# Generated by Django 4.2.20 on 2025-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.SlugField(blank=True, null=True, verbose_name='Имя пользователя в Telegram'),
        ),
    ]
