# Generated by Django 4.2.20 on 2025-05-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-start_date',), 'verbose_name': 'образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-start_date',), 'verbose_name': 'опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterModelOptions(
            name='hardskill',
            options={'ordering': ('grid_row', 'grid_column', 'updated_at'), 'verbose_name': 'проффесиональный навык', 'verbose_name_plural': 'Профессиональные навыки'},
        ),
        migrations.AlterModelOptions(
            name='softskill',
            options={'ordering': ('grid_row', 'grid_column', 'updated_at'), 'verbose_name': 'личностный навык', 'verbose_name_plural': 'Личностные навыки'},
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255, verbose_name='Степень (курсы)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=255, verbose_name='Специальность (направление)'),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_educations', to='user.education'),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_educations', to='user.resume'),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_experiences', to='user.experience'),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_experiences', to='user.resume'),
        ),
    ]
