# Generated by Django 4.2.20 on 2025-05-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
