# Generated by Django 4.2.20 on 2025-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(db_index=True, max_length=255, verbose_name='Должность')),
                ('category', models.CharField(db_index=True, max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.RemoveConstraint(
            model_name='resume',
            name='unique_resume',
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('position', 'category'), name='unique_position'),
        ),
    ]
