# Generated by Django 4.2.20 on 2025-05-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_position_remove_resume_unique_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='user.position', verbose_name='Позиция'),
        ),
    ]
