# Generated by Django 4.2.20 on 2025-05-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_resume_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('-category', '-position'), 'verbose_name': 'должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='user.position', verbose_name='Позиция'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(fields=('user', 'position'), name='unique_resume'),
        ),
    ]
