# Generated by Django 4.2.20 on 2025-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_position_options_alter_resume_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='education',
            name='unique_education',
        ),
        migrations.RemoveConstraint(
            model_name='experience',
            name='unique_experience',
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('user', 'institution', 'start_date'), name='unique_education'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'start_date'), name='unique_experience'),
        ),
    ]
