# Generated by Django 4.2.20 on 2025-05-29 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_education_unique_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_me',
            field=models.TextField(help_text='Максимум 1024 символов', validators=[django.core.validators.MaxLengthValidator(1024)], verbose_name='Обо мне'),
        ),
    ]
